name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: API Tests (Playwright)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e-api
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm run test:api

      - name: Upload relatório API
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-api
          path: playwright-report/

  e2e-tests:
    name: E2E Tests (Cucumber + Playwright)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e-api
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install  

      - name: Run E2E tests
        run: npm run test:all

      - name: Upload relatório E2E
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-e2e
          path: reports/

  mobile-tests:
    name: Mobile Tests (Appium)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Skip Mobile Tests (placeholder)
        run: echo "Executar localmente para testes reais."

      - name: Upload relatório Mobile
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-mobile
          path: allure-report/

  load-tests:
    name: Load Test (K6)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./carga
    steps:
      - uses: actions/checkout@v3

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo gpg -k || true
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k6.gpg
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Run Load Test
        run: k6 run tests/load-test.js

      - name: Upload relatório Carga
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-carga
          path: reports/

  upload-relatorios:
    name: Upload Relatorios Unificados
    runs-on: ubuntu-latest
    needs: [api-tests, e2e-tests, mobile-tests, load-tests]
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Baixar relatório API
        uses: actions/download-artifact@v4
        with:
          name: relatorio-api
          path: relatorios/api

      - name: Baixar relatório E2E
        uses: actions/download-artifact@v4
        with:
          name: relatorio-e2e
          path: relatorios/e2e

      - name: Baixar relatório Mobile
        uses: actions/download-artifact@v4
        with:
          name: relatorio-mobile
          path: relatorios/mobile

      - name: Baixar relatório Carga
        uses: actions/download-artifact@v4
        with:
          name: relatorio-carga
          path: relatorios/carga

      - name: Upload final dos relatórios unificados
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-gerais
          path: relatorios/
